AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - db/**/*.rb
  - lib/tasks/**/*.rake
  - config/initializers/*.rb
  - vendor/**/*
  - tmp/**/*
  - bin/**/*

Metrics/BlockLength:
  Max: 25
  Exclude:
  - config/routes.rb
  - spec/**/*.rb
  - 'Rakefile'
  - '**/*.rake'

Style/Documentation:
  Enabled: false
