AllCops:
  TargetRubyVersion: 2.3
  Exclude:
  - db/**/*.rb
  - lib/tasks/**/*.rake
  - config/initializers/*.rb

Metrics/BlockLength:
  Max: 25
  Exclude:
  - config/routes.rb
  - spec/**/*.rb
  - 'Rakefile'
  - '**/*.rake'

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 25

Metrics/ClassLength:
  Max: 100
  Exclude:
  - app/models/travels/trip.rb
