# Offense count: 1
# Cop supports --auto-correct.
# Configuration parameters: AllowUnusedKeywordArguments, IgnoreEmptyMethods.
AllCops:
  TargetRubyVersion: 2.3

# Offense count: 4
# Configuration parameters: CountComments.
Metrics/BlockLength:
  Max: 25
  Exclude:
  - config/routes.rb
  - spec/**/*.rb
  - 'Rakefile'
  - '**/*.rake'

Style/Documentation:
  Enabled: false
