language: ruby
rvm:
  - 2.1.2
services:
  - redis-server
  - memcached
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - bundle exec rspec
before_script:
  - psql -c 'create database travel_planner_test;' -U postgres
notifications:
  slack: hamstertravel:0cUdYv5PqtYYExONQ7d4SJg5