language: ruby
sudo: false
cache: bundler
rvm:
  - 2.2.4
services:
  - redis-server
  - memcached
script:
  - bundle exec rspec
before_script:
  - psql -c 'create database travel_planner_test;' -U postgres
  - RAILS_ENV=test bundle exec rake --trace db:migrate
notifications:
  slack: hamstertravel:0cUdYv5PqtYYExONQ7d4SJg5