version: '2'
services:
  box:
    image: busybox
    volumes:
      - /box
  database:
    image: postgres:9.6
    ports:
      - '15432:5432'
    volumes:
      - ./db:/var/dump
      - /var/lib/postgresql/data
  redis:
    image: redis
  web:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: hamster-travel
    command: foreman start
    links:
      - database
      - redis
    volumes:
      - .:/opt/hamster-travel
    volumes_from:
      - box
    ports:
      - '13000:3000'
      - '8080:8080'
    environment:
      REDIS_HOST: redis
      POSTGRES_HOST: database
