development:
  adapter: postgresql
  encoding: unicode
  database: travel_planner_development
  pool: 5
  username: postgres
  password:
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: travel_planner_test
  pool: 5
  username: postgres
  password:
  host: <%= ENV['POSTGRES_HOST'] || 'localhost' %>
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  database: travel_planner_production
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  port: 5432
