s3:
  key: <%= ENV['AWS_S3_KEY'] %>
  secret: <%= ENV['AWS_S3_SECRET'] %>
images:
  base_url: 'https://s3.eu-central-1.amazonaws.com/hamster-travel-images'
  flags_folder: 'flags'
rollbar:
  token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
