app_host: http://hamster.travel
s3:
  key: <%= ENV['AWS_S3_KEY'] %>
  secret: <%= ENV['AWS_S3_SECRET'] %>
images:
  base_url: 'https://s3.eu-central-1.amazonaws.com/hamster-travel-images'
  flags_folder: 'flags'
rollbar:
  token: <%= ENV['ROLLBAR_ACCESS_TOKEN'] %>
new_relic:
  license_key: <%= ENV['NEW_RELIC_LICENSE_KEY'] %>
mapbox:
  token: <%= ENV['MAPBOX_TOKEN'] %>
redis:
  host: <%= ENV['REDIS_HOST'] %>
smtp:
  address: <%= ENV['SMTP_ADDRESS'] %>
  port: <%= ENV['SMTP_PORT'] %>
  username: <%= ENV['SMTP_USERNAME'] %>
  password: <%= ENV['SMTP_PASSWORD'] %>
  authentication: <%= ENV['SMTP_AUTHENTICATION'] %>
  enable_starttls_auto: <%= ENV['SMTP_ENABLE_STARTTLS_AUTO'] %>
